# rule identifiers to opt in
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - force_unwrapping
  - implicit_return
  
disabled_rules:
  - trailing_whitespace
  - weak_delegate

# special configuration for rules 
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false

file_length:
  warning: 400
  error: 1000

function_body_length:
  warning: 40
  error: 100

function_parameter_count:
  warning: 5
  error: 8

large_tuple:
  warning: 2
  error: 3

line_length:
  warning: 180
  error: 200
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: false

